### ISSUE TITLE
Help configuring CI, got error: src refspec master does not match any

### ISSUE THREAD

**Issue by uwla** [orhun/git-cliff-action#37]
Hi, I was trying to configure the CI just as in #13,
but I got `error: src refspec master does not match any` even though the branch is set to `master` which is the default and only branch of my repo.

![2024-09-17_19-40](https://github.com/user-attachments/assets/7f8a8d91-fab6-4614-9261-14d9f98edaf0)
![2024-09-17_19-41](https://github.com/user-attachments/assets/e33435b7-52fa-41e6-8802-c65e611e6624)

Here is the failed job <https://github.com/uwla/justify.js/actions/runs/10912220367/job/30286442176>.

What did I do wrong?

**Comment by orhun** [comment]
Hello! 👋🏼 

It turns out when you trigger the workflow from a tag (i.e. `on` -> `push` -> `tags`), it doesn't check out the branch as default. So you need to run `git checkout <branch>` before attempting to commit/push your changes.

You can see that it checks out `HEAD` as detached from the logs:

```
[detached HEAD 3783b78] docs: update CHANGELOG
```

Updated the example in 39dc6a758b17b1d3a2043b328954d31566d2d084

Can you try it out? :)

**Comment by orhun** [comment]
You need to go to `Repository` -> `Settings` -> `Actions` -> `General` and allow `Read and Write permissions` for the workflows I think. Can you do that and confirm if it works? I can update the documentation based on that.

**Comment by orhun** [comment]
Awesome, updated the documentation in 47c2a7feddeedd338efa21e865d054c2487e4700

> your projects rocks! Been following you since a while

Thank you!
